---
  host:
    description: "Consul server IP/name.  Default 127.0.0.1"
    type: "string"
    secret: false
    required: true
    default: "127.0.0.1"
  port:
    description: "Consul server port. Default 8500"
    type: "integer"
    secret: false
    required: true
    default: 8500
  token:
    description: "Consul API token"
    type: "string"
    secret: true
    required: true
  scheme:
    description: "Consul scheme to use. Default http"
    type: "string"
    required: false
    default: "http"
  verify:
    description: "Verify the SSL certificate for HTTPS requests. Default false"
    type: "boolean"
    required: false
    default: false
  consistency:
    description: "The consistency mode to use by default for all reads that support the consistency option."
    type: "string"
    enum:
      - default
      - consistent
      - stale
    required: false
    default: "default"
